package it.polito.ai.lhmf.orm;

// Generated 25-lug-2012 11.32.27 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MemberStatus generated by hbm2java
 */
@Entity
@Table(name = "member_status", catalog = "malnati_project")
public class MemberStatus implements java.io.Serializable {

	private int idMemberStatus;
	private String description;
	private Set members = new HashSet(0);

	public MemberStatus() {
	}

	public MemberStatus(int idMemberStatus) {
		this.idMemberStatus = idMemberStatus;
	}

	public MemberStatus(int idMemberStatus, String description, Set members) {
		this.idMemberStatus = idMemberStatus;
		this.description = description;
		this.members = members;
	}

	@Id
	@Column(name = "idMember_Status", unique = true, nullable = false)
	public int getIdMemberStatus() {
		return this.idMemberStatus;
	}

	public void setIdMemberStatus(int idMemberStatus) {
		this.idMemberStatus = idMemberStatus;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memberStatus")
	public Set getMembers() {
		return this.members;
	}

	public void setMembers(Set members) {
		this.members = members;
	}

}
