package it.polito.ai.gasproject.orm;

// Generated 7-giu-2012 22.56.48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductCategory generated by hbm2java
 */
@Entity
@Table(name = "product_category", catalog = "malnati_project")
public class ProductCategory implements java.io.Serializable {

	private int idProductCategory;
	private String description;
	private Set products = new HashSet(0);

	public ProductCategory() {
	}

	public ProductCategory(int idProductCategory, String description) {
		this.idProductCategory = idProductCategory;
		this.description = description;
	}

	public ProductCategory(int idProductCategory, String description,
			Set products) {
		this.idProductCategory = idProductCategory;
		this.description = description;
		this.products = products;
	}

	@Id
	@Column(name = "idProduct_Category", unique = true, nullable = false)
	public int getIdProductCategory() {
		return this.idProductCategory;
	}

	public void setIdProductCategory(int idProductCategory) {
		this.idProductCategory = idProductCategory;
	}

	@Column(name = "description", nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productCategory")
	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
