package it.polito.ai.lhmf.orm;

// Generated 8-giu-2012 18.52.32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "malnati_project")
public class Message implements java.io.Serializable {

	private Integer idMessage;
	private Member memberByIdReceiver;
	private Member memberByIdSender;
	private String text;
	private Date messageTimestamp;

	public Message() {
	}

	public Message(Member memberByIdReceiver, Member memberByIdSender,
			String text, Date messageTimestamp) {
		this.memberByIdReceiver = memberByIdReceiver;
		this.memberByIdSender = memberByIdSender;
		this.text = text;
		this.messageTimestamp = messageTimestamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMessage", unique = true, nullable = false)
	public Integer getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(Integer idMessage) {
		this.idMessage = idMessage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_receiver", nullable = false)
	public Member getMemberByIdReceiver() {
		return this.memberByIdReceiver;
	}

	public void setMemberByIdReceiver(Member memberByIdReceiver) {
		this.memberByIdReceiver = memberByIdReceiver;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sender", nullable = false)
	public Member getMemberByIdSender() {
		return this.memberByIdSender;
	}

	public void setMemberByIdSender(Member memberByIdSender) {
		this.memberByIdSender = memberByIdSender;
	}

	@Column(name = "text", nullable = false, length = 300)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "message_timestamp", nullable = false, length = 19)
	public Date getMessageTimestamp() {
		return this.messageTimestamp;
	}

	public void setMessageTimestamp(Date messageTimestamp) {
		this.messageTimestamp = messageTimestamp;
	}

}
