package it.polito.ai.lhmf.orm;



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderProductId generated by hbm2java
 */
@Embeddable
public class OrderProductId implements java.io.Serializable {

	private int idOrder;
	private int idProduct;

	public OrderProductId() {
	}

	public OrderProductId(int idOrder, int idProduct) {
		this.idOrder = idOrder;
		this.idProduct = idProduct;
	}

	@Column(name = "idOrder", nullable = false)
	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

	@Column(name = "idProduct", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderProductId))
			return false;
		OrderProductId castOther = (OrderProductId) other;

		return (this.getIdOrder() == castOther.getIdOrder())
				&& (this.getIdProduct() == castOther.getIdProduct());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOrder();
		result = 37 * result + this.getIdProduct();
		return result;
	}

}
