package it.polito.ai.lhmf.orm;



import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderProduct generated by hbm2java
 */
@Entity
@Table(name = "order_product", catalog = "malnati_project")
public class OrderProduct implements java.io.Serializable {

	private OrderProductId id;
	private Order order;
	private Product product;
	private boolean failed;

	public OrderProduct() {
	}

	public OrderProduct(OrderProductId id, Order order, Product product,
			boolean failed) {
		this.id = id;
		this.order = order;
		this.product = product;
		this.failed = failed;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idOrder", column = @Column(name = "idOrder", nullable = false)),
			@AttributeOverride(name = "idProduct", column = @Column(name = "idProduct", nullable = false)) })
	public OrderProductId getId() {
		return this.id;
	}

	public void setId(OrderProductId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idOrder", nullable = false, insertable = false, updatable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProduct", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "failed", nullable = false)
	public boolean isFailed() {
		return this.failed;
	}

	public void setFailed(boolean failed) {
		this.failed = failed;
	}

}
