package it.polito.ai.lhmf.orm;

// Generated 24-lug-2012 21.25.07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductCategory generated by hbm2java
 */
@Entity
@Table(name = "product_category", catalog = "malnati_project")
public class ProductCategory implements java.io.Serializable {

	private Integer idProductCategory;
	private String description;
	private Set products = new HashSet(0);

	public ProductCategory() {
	}

	public ProductCategory(String description) {
		this.description = description;
	}

	public ProductCategory(String description, Set products) {
		this.description = description;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idProduct_Category", unique = true, nullable = false)
	public Integer getIdProductCategory() {
		return this.idProductCategory;
	}

	public void setIdProductCategory(Integer idProductCategory) {
		this.idProductCategory = idProductCategory;
	}

	@Column(name = "description", nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productCategory")
	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
