package it.polito.ai.gasproject.orm;

// Generated 7-giu-2012 22.56.48 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notify generated by hbm2java
 */
@Entity
@Table(name = "notify", catalog = "malnati_project")
public class Notify implements java.io.Serializable {

	private Integer idNotify;
	private Member member;
	private int text;

	public Notify() {
	}

	public Notify(Member member, int text) {
		this.member = member;
		this.text = text;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idNotify", unique = true, nullable = false)
	public Integer getIdNotify() {
		return this.idNotify;
	}

	public void setIdNotify(Integer idNotify) {
		this.idNotify = idNotify;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMember", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "text", nullable = false)
	public int getText() {
		return this.text;
	}

	public void setText(int text) {
		this.text = text;
	}

}
